#
#   author: Tyranzx
#   us@stellarsquad
#
lang: en
# DATABASE SETTINGS
mysql:
  host: 127.0.0.1
  port: 3306
  username: root@localhost
  password: "123you_a_fool321"
  ssl: false
# SERVER SETTINGS
settings:
  board: false
  join_items: false
  tablist: false
  prevention:
    flintsteelItem: true
    staffsocket: false
    nobuild: true
# SERVER INTEGRATED PLUGINS SETTINGS
plugins:
  enderpearlrider: true
  luckyblocks: false
  hookapi: true
  backpacks:
    enabled: true
    size: 18
  jumppad: true
  throwable-tnt:
    power: 3F
    fuego: false
    multiplicador: 2
    drop: false
